### ISSUE TITLE
TODO: annontate exchange accounts

### ISSUE THREAD

**Issue by jaekwon** [gnolang/independence-day#12]
We need to crowdsource the annotation of exchange accounts. 

In the end, we can have legal-ese to exclude exchanges and require them to not touch those coins, with risk of on-chain penalty (and future! penalty under gno.land jurisdiction & sovereignty). But not everyone will comply, so we should put the effort into freezing them.

What we do with the frozen GNOTs is ultimately up to the GNOT holders (also with natural veto power by gno.land SHARE holders, of a proof-of-contribution system). Perhaps used in negotiations, perhaps forever ignored.

TODO:
- [ ] make a file (contributions.md) and list to contributions in this effort by the community.
- [ ] reward them upon genesis.
- [ ] draft legal-ese also for exchanges.

**Comment by KorNatten** [comment]
Is someone working on this? I'm willing to manually check everything. Like HUOBI has 2 different validators now. HUOBI and HUOBI1, I asked catdotfish about it in a video and she didn't know if it's someone just using the name or if they're the same.
There's many strange things with Hub validators lately.

Also like in this file, there's big accounts with 0 Atoms and no tx history on mintscan
https://gist.github.com/moul/b1eab022e24eafa5a158d32ac6f24ab7

**Comment by moul** [comment]
contributions.md is bootstrapped, I'll updated it progressively.

everyone -> ping me if I miss some contributions.

**Comment by KorNatten** [comment]
I've been working on the CEX validators, you can see here what I'm doing and feel free to let me know what more should be done or added. [personal repo](https://github.com/KorNatten/Cosmos-centralised-validator)

**Comment by moul** [comment]
I've a 404; is the repo private?

**Comment by KorNatten** [comment]
It was sorry, now it's public

**Comment by moul** [comment]
can you check the link? I still have a 404 here: https://github.com/KorNatten/Cosmos-centralised-validator

**Comment by KorNatten** [comment]
It'strange, maybe try https://github.com/KorNatten/Cosmos-centralised-validators/blob/main/README.md
and the csv is https://github.com/KorNatten/Cosmos-centralised-validators/blob/main/cosmos-validators-info%20-%20validators-height-10562840.csv

**Comment by moul** [comment]
Ok now I've access, I will give a look.

In the meantime, I was working on #16 and generated this list for top accounts (liquid + staked + unbounding): https://gist.github.com/moul/29c0df4055df019a91440521a02dc23e.

**Comment by moul** [comment]
Ok, I reviewed your work. Can you tell me which part was manually crafted and which part was generated or found?

I'm particularly interested if you have commands to run to regenerate the same results. I need to make a second check to see if I find the same values.

Thank you for your help.

**Comment by KorNatten** [comment]
The readme, explains every step I made https://github.com/KorNatten/Cosmos-centralised-validators/blob/main/README.md
Everything was done manually based on existing files and mintscan.
At the bottom of the readme, there's a link to the spreadsheet, that I just saved as a .cvs to upload on github. I kept the spreadsheet online so you might be able to sort it, the way you want.

I did not run commands, I don't know how, sorry.

**Comment by KorNatten** [comment]
I also checked the top 50 from your gist file and added some more comments, https://github.com/KorNatten/independence-day/blob/main/Moul_Gist_top_50_check_and_comments.csv
