### ISSUE TITLE
[META] independence-day

### ISSUE THREAD

**Issue by moul** [gnolang/independence-day#13]
## Description

- 350M GNOT to be airdropped to select Cosmos wallets ([snapshot](https://github.com/gnolang/independence-day/blob/main/snapshot/cosmoshub_snapshot.md))
- 231M GNOT to be airdropped to ATONE and PHOTON holders (block [6439117](https://www.mintscan.io/atomone/block/6439117)). ATONE and PHOTON should be valued 1:1 for the purpose of proportional distribution.
- 119M GNOT will be allocated to Gno.land contributors. These funds will be placed in a multisig wallet and will be distributed at a later date by a subDAO.

---

Open questions and TODOs:
* [ ] Update the Cosmos distribution from 700M to 350M
* [ ] Identify and add ATONE addresses to `excluded.txt`
* [ ] Distribute 231M GNOT to ATONE and PHOTON holder addresses
* [ ] Consolidate amounts for addresses that are in the Cosmos and ATONE/PHOTON airdrops
* [ ] What is the multisig wallet address for Gno.land contributors?

**Comment by thehowl** [comment]
Closing :)
